$NAME_STR "Survivor Shelter"

; A hotel: where survivors (the game's tourists) stay while they decide.

-------
$COST_WORK SOVIET_CONSTRUCTION_GROUNDWORKS 0.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO ground_asphalt 0.03
------------------
$COST_WORK SOVIET_CONSTRUCTION_STEEL_LAYING 1.0
$COST_WORK_BUILDING_ALL
$COST_RESOURCE_AUTO wall_steel 0.2
-----------------------

$TYPE_HOTEL
$WORKERS_NEEDED 8
$CITIZEN_ABLE_SERVE 3
$ELETRIC_WITHOUT_WORKING_FACTOR 0.5
$ELETRIC_WITHOUT_LIGHTING_FACTOR 0.2
$ATTRACTIVE_SCORE 1.6
$ATTRACTIVE_FACTOR_SIGHT 0.25
$ATTRACTIVE_FACTOR_SIGHT_ADD 0.35
$ATTRACTIVE_FACTOR_NATURE 0.25
$ATTRACTIVE_FACTOR_NATURE_ADD 0.25
$ATTRACTIVE_FACTOR_POLLUTION 0.25
$ATTRACTIVE_FACTOR_POLLUTION_ADD 0.25
$STORAGE_DEMAND_HOTEL RESOURCE_TRANSPORT_COVERED 16
$STORAGE_DEMAND_HOTEL RESOURCE_TRANSPORT_COOLER 2

$VEHICLE_STATION -2.0 0 -1.0  -2.0 0 9.5
$VEHICLE_STATION  2.0 0 -1.0   2.0 0 9.5

$CONNECTIONS_ROAD_DEAD_SQUARE
-17.5 13.5
17.5 -13.5

$CONNECTION_ROAD
0.0 0.0 15.0
0.0 0.0 13.5
$CONNECTION_PEDESTRIAN
-7.0 0.0 13.5
-7.0 0.0 15.0
$CONNECTION_PEDESTRIAN
7.0 0.0 13.5
7.0 0.0 15.0

end
